version: '3.7'

services:

  user-service:
    image: user-service:latest
    env_file:
      - ./user-service/.env
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - DATABASE_URL=postgres://postgres:password@postgresdb:5432/users

  product-service:
    image: product-service:latest
    env_file:
      - ./product-service/.env
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    environment:
      - DATABASE_URL=postgres://postgres:password@postgresdb:5432/products

  
  order-service:
    image: order-service:latest
    env_file:
      - ./order-service/.env
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    environment:
      - DATABASE_URL=postgres://postgres:password@postgresdb:5432/orders

  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce

  kafka-1:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-1:19092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:19092,OUTSIDE://0.0.0.0:9092

  kafka-2:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-2:19093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:19093

  kafka-3:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-3:19094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:19094

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
